### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wjw0129** [ghosind/ExamSystem#1]
请问怎么解决？
![空指针](https://user-images.githubusercontent.com/37805786/54491476-cfb03900-48f9-11e9-84f6-de82fc685f19.png)

**Comment by ghosind** [comment]
hi,
当登陆的用户的身份为管理员时，登陆后的导航栏上会有一个“管理”按钮，点击后就可以进入。

**Comment by ghosind** [comment]
hi,
当登陆的用户的身份为管理员时，登陆后的导航栏上会有一个“管理”按钮，点击后就可以进入。

**Comment by wjw0129** [comment]
OK，thank you.
