### ISSUE TITLE
项目启动运行失败

### ISSUE THREAD

**Issue by CodeFishK** [ghosind/ExamSystem#4]
你好作者，启动项目时，报错如下图！
![image](https://user-images.githubusercontent.com/38446347/113661771-4d119680-96d9-11eb-9f42-893a3d7420e1.png)

**Comment by ghosind** [comment]
你好😃 ，根据你的截图看来似乎是项目中使用的部分NuGet包没有下载。

抱歉我已经很多年不使用C#开发了，没有办法自己验证，只有在网上找了一篇相关的文章，希望能够帮到你
https://www.cnblogs.com/xielong/p/7691142.html

另外，感谢你对这个项目的支持，但是这个项目是我多年前还在上学的时候写的，有许多地方存在不合理的设计，望周知。

**Comment by CodeFishK** [comment]
> 你好😃 ，根据你的截图看来似乎是项目中使用的部分NuGet包没有下载。
> 
> 抱歉我已经很多年不使用C#开发了，没有办法自己验证，只有在网上找了一篇相关的文章，希望能够帮到你
> https://www.cnblogs.com/xielong/p/7691142.html
> 
> 另外，感谢你对这个项目的支持，但是这个项目是我多年前还在上学的时候写的，有许多地方存在不合理的设计，望周知。

感谢前辈，最近在搞毕业设计，所以想学习下你项目，我尝试下你提供帮助，万分感谢！
